---
- name: copy pf.conf
  copy:
    src: "{{ firewall_src }}"
    dest: /etc/pf.conf
    mode: 0600
    owner: root
    group: wheel
  notify: reload pf
  when: firewall_src is defined

- name: create pf.conf from template
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    mode: 0600
    owner: root
    group: wheel
  notify: reload pf
  when: firewall_src is not defined
