---
- name: remove firewalld
  package:
    name: firewalld
    state: removed

- name: install iptables-services
  package:
    name: iptables-services
    state: installed

- name: create iptables config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    mode: 0600
    owner: root
    group: root
  notify: "reload {{ item }}"
  with_items:
    - iptables
    - ip6tables

- name: enable iptables service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - iptables
    - ip6tables
