---
- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: remove firewalld
  package:
    name: firewalld
    state: removed

- name: install iptables packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ firewall_packages }}"

- name: copy iptables config
  template:
    src: "{{ firewall_src[item] }}"
    dest: "/etc/sysconfig/{{ item }}"
    mode: 0600
    owner: root
    group: root
  notify: "reload {{ item }}"
  with_items:
    - iptables
    - ip6tables
  when: firewall_src is defined

- name: create iptables config from template
  template:
    src: "{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    mode: 0600
    owner: root
    group: root
  notify: "reload {{ item }}"
  with_items:
    - iptables
    - ip6tables
  when: firewall_src is not defined

- name: enable iptables service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - iptables
    - ip6tables
