---
- block:
  - name: install sysstat package
    package:
      name: sysstat
      state: installed

  - name: enable power statistics
    lineinfile:
      path: /etc/sysconfig/sysstat
      regexp: '^SADC_OPTIONS='
      line: 'SADC_OPTIONS="-S DISK -S POWER -S XDISK"'
    when: ansible_virtualization_role != "guest"

  - name: enable sysstat service
    service:
      name: sysstat
      enabled: yes
  when: ansible_system == "Linux"
