version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2
     steps:
       - checkout
       - run: sudo pip install ansible-lint
       - run: ansible-lint --version
       - run: find . -type d -mindepth 1 -maxdepth 1 '!' -name '.*' -execdir ansible-lint -v '{}' +
