---
- name: include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install vnstat
  package:
    name: "{{ vnstat_package }}"
    state: installed

- name: enable vnstatd
  service:
    name: "{{ vnstat_service }}"
    state: started
    enabled: yes
