---
- name: set authorized keys for root
  authorized_key:
    state: present
    user: root
    key: "{{ ssh_authorized_keys|join('\n') }}"
    exclusive: "{{ ssh_authorized_keys_exclusive|default('yes') }}"
  when: ssh_authorized_keys is defined
