---
- include_vars: "{{ ansible_os_family }}.yml"

- name: install ntpd package
  package:
    name: "{{ ntpd_package }}"
    state: installed
  when: ntpd_package is defined

- name: configure ntpd
  template:
    src: "{{ ntpd_template }}"
    dest: "{{ ntpd_config }}"
    mode: 0644
    owner: root
    group: "{{ ansible_wheel }}"
  notify: restart ntpd

- name: enable ntpd service
  service:
    name: "{{ ntpd_service }}"
    state: started
    enabled: yes
