---
- name: install denyhosts
  package:
    name: denyhosts
    state: installed

- name: configure denyhosts
  lineinfile:
    path: /etc/denyhosts.conf
    regexp: '^[#\s]*{{ item.key }}\s*='
    line: '{{ item.key}} = {{ item.value }}'
  with_dict:
    DENY_THRESHOLD_INVALID: 10
    DENY_THRESHOLD_VALID: 10
    DENY_THRESHOLD_ROOT: 10
    ADMIN_EMAIL: ""
    SYSLOG_REPORT: "YES"
    RESET_ON_SUCCESS: "YES"
  notify: restart denyhosts

- name: configure denyhosts whitelist
  copy:
    content: "{{ ['127.0.0.1']|union(denyhosts_whitelist)|join('\n') }}\n"
    dest: /var/lib/denyhosts/allowed-hosts
    mode: 0644
    owner: root
    group: root
  notify: restart denyhosts

- name: enable denyhosts service
  service:
    name: denyhosts
    state: started
    enabled: yes
